/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GapsRouteImport } from './routes/gaps'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorIndexRouteImport } from './routes/editor.index'
import { Route as EditorScriptIdRouteImport } from './routes/editor.$scriptId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiPublicHooksWeeklyGapDigestRouteImport } from './routes/api/public/hooks/weekly-gap-digest'

const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsRoute = GapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorRoute,
} as any)
const EditorScriptIdRoute = EditorScriptIdRouteImport.update({
  id: '/$scriptId',
  path: '/$scriptId',
  getParentRoute: () => EditorRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWeeklyGapDigestRoute =
  ApiPublicHooksWeeklyGapDigestRouteImport.update({
    id: '/api/public/hooks/weekly-gap-digest',
    path: '/api/public/hooks/weekly-gap-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRouteWithChildren
  '/gaps': typeof GapsRoute
  '/join': typeof JoinRoute
  '/navigator': typeof NavigatorRoute
  '/signals': typeof SignalsRoute
  '/admin/users': typeof AdminUsersRoute
  '/editor/$scriptId': typeof EditorScriptIdRoute
  '/editor/': typeof EditorIndexRoute
  '/api/public/hooks/weekly-gap-digest': typeof ApiPublicHooksWeeklyGapDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gaps': typeof GapsRoute
  '/join': typeof JoinRoute
  '/navigator': typeof NavigatorRoute
  '/signals': typeof SignalsRoute
  '/admin/users': typeof AdminUsersRoute
  '/editor/$scriptId': typeof EditorScriptIdRoute
  '/editor': typeof EditorIndexRoute
  '/api/public/hooks/weekly-gap-digest': typeof ApiPublicHooksWeeklyGapDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRouteWithChildren
  '/gaps': typeof GapsRoute
  '/join': typeof JoinRoute
  '/navigator': typeof NavigatorRoute
  '/signals': typeof SignalsRoute
  '/admin/users': typeof AdminUsersRoute
  '/editor/$scriptId': typeof EditorScriptIdRoute
  '/editor/': typeof EditorIndexRoute
  '/api/public/hooks/weekly-gap-digest': typeof ApiPublicHooksWeeklyGapDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/editor'
    | '/gaps'
    | '/join'
    | '/navigator'
    | '/signals'
    | '/admin/users'
    | '/editor/$scriptId'
    | '/editor/'
    | '/api/public/hooks/weekly-gap-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/gaps'
    | '/join'
    | '/navigator'
    | '/signals'
    | '/admin/users'
    | '/editor/$scriptId'
    | '/editor'
    | '/api/public/hooks/weekly-gap-digest'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/editor'
    | '/gaps'
    | '/join'
    | '/navigator'
    | '/signals'
    | '/admin/users'
    | '/editor/$scriptId'
    | '/editor/'
    | '/api/public/hooks/weekly-gap-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EditorRoute: typeof EditorRouteWithChildren
  GapsRoute: typeof GapsRoute
  JoinRoute: typeof JoinRoute
  NavigatorRoute: typeof NavigatorRoute
  SignalsRoute: typeof SignalsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiPublicHooksWeeklyGapDigestRoute: typeof ApiPublicHooksWeeklyGapDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps': {
      id: '/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof GapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/$scriptId': {
      id: '/editor/$scriptId'
      path: '/$scriptId'
      fullPath: '/editor/$scriptId'
      preLoaderRoute: typeof EditorScriptIdRouteImport
      parentRoute: typeof EditorRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-gap-digest': {
      id: '/api/public/hooks/weekly-gap-digest'
      path: '/api/public/hooks/weekly-gap-digest'
      fullPath: '/api/public/hooks/weekly-gap-digest'
      preLoaderRoute: typeof ApiPublicHooksWeeklyGapDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EditorRouteChildren {
  EditorScriptIdRoute: typeof EditorScriptIdRoute
  EditorIndexRoute: typeof EditorIndexRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorScriptIdRoute: EditorScriptIdRoute,
  EditorIndexRoute: EditorIndexRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EditorRoute: EditorRouteWithChildren,
  GapsRoute: GapsRoute,
  JoinRoute: JoinRoute,
  NavigatorRoute: NavigatorRoute,
  SignalsRoute: SignalsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiPublicHooksWeeklyGapDigestRoute: ApiPublicHooksWeeklyGapDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
